on: 
  issue_comment:
    types: [edited, created]

jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:        
    - uses: Amadevus/pwsh-script@v2
      name: Dump event
      with:
        script: |             
          Write-ActionInfo ($github.event.issue | Convertto-Json -Depth 100) 
