on: 
  issue_comment:
    types: [edited, created]

jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for urls
      id: check-url
      run: |
        BODY='${{ github.event.comment.body }}'
        PATTERN="https:\/\/dev\.azure\.com\/[^\/]+\/[^\/]+\/_git\/[^\/]+\/pullrequest\/[[:digit:]]+"
        URL=$(echo $BODY | grep -oE $PATTERN)
        CNT=$(echo $BODY | grep -oE $PATTERN | wc -l)
        echo "::set-output name=URL::'$URL'"
        echo "::set-output name=CNT::'$CNT'"
        
    - uses: Amadevus/pwsh-script@v2
      if: ${{ steps.check-url.outputs.CNT }} == 1
      name: Dump event
      with:
        script: |             
          Write-ActionInfo "${{ steps.check-url.outputs.URL }}"
