on: 
  issue_comment:
    types: [edited, created]

jobs:
  issue_commented:
    name: Issue comment
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    steps:
    - name: Check for urls
      id: check-url
      run: |
        URL=$(echo '${{ github.event.comment.body }}' | grep -oE "https:\/\/dev\.azure\.com\/[^\/]+\/[^\/]+\/_git\/[^\/]+\/pullrequest\/[[:digit:]]+")
        echo "::set-output name=URL::'$URL'"
        
    - uses: Amadevus/pwsh-script@v2
      if: ${{ steps.check-url.outputs.URL }}
      name: Dump event
      with:
        script: |             
          Write-ActionInfo "${{ steps.check-url.outputs.URL }}"
