on:
  pull_request:
    types: [labeled, edited, opened, synchronize, reopened]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        
    - uses: Amadevus/pwsh-script@v2
      name: Dump event
      with:
        script: |             
          Write-ActionInfo ($github.event.pull_request.author)        
