name: Add Issue to Memex

on:
  pull_request:
    types: [labeled]
  issues:
    types: [labeled]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        
    - uses: Amadevus/pwsh-script@v2
      name: Dump event
      with:
        script: |   
          $triggerItem = $github.event.issue ?? $github.event.pull_request
          $itemId = $triggerItem.node_id
          
          Write-ActionInfo ($itemId)        
