name: Add Issue to Memex

on:
  pull_request:
    types: [labeled]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        
    - uses: Amadevus/pwsh-script@v2
      name: Dump event
      with:
        script: |       
          Write-ActionInfo ($github.event | convertto-json -depth 100)        
