on:
  pull_request:
    types: [labeled, edited, opened, synchronize, reopened, closed]

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
        
    - uses: Amadevus/pwsh-script@v2
      name: Dump event
      with:
        script: |             
          Write-ActionInfo (ConvertTo-Json -Depth 100 $github.event.pull_request)        
